# values.yaml
controller:
  replicaCount: 2
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

defaultBackend:
  enabled: true
  replicaCount: 1